### ISSUE TITLE
Convert from JPOS XML message

### ISSUE THREAD

**Issue by mohammadi-hamid** [chuksynaza/cISO8583#1]
Hi
How can I parse XML messages received from JPOS server?

**Comment by chuksynaza** [comment]
Hi @HamidMohammadi, can you post a sample of the XML message and what exactly you are trying to achieve?

**Comment by mohammadi-hamid** [comment]
@chuksynaza Thanks for your reply.
We used XMLPackager in our project. I want to convert XML received data from a socket to and change it some data, then send back to the server. 
In another way, can I create custom packager?

**Comment by chuksynaza** [comment]
From your response I understand you want to modify some fields in the XML data returned from XMLPackager, then repack it as an ISO8583 message and send it back to the server.

This library can help you repack the ISO message using the ` cISO8583.pack()` method.

If you go through the documentation you'd see how simple it can be, all you'd need to do is structure the fields and respective data as JSON in `dataElements` form below and then call the pack() method.

```

const cISO8583 = require('ciso8583');
 
let iso8583Parser = new cISO8583();

let dataElements = {
    '2': '1234567890123456',
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '7': '0609173030',
    ...
};

let MTI = '0200';
 
let packed = iso8583Parser.pack(MTI, dataElements);
 
//This returns the packed ISO8583 message
console.log(packed.isoMessage);

```

You can also use this library to unpack the messages from the socket by passing the data into the `cISO8583.unpack()`, feel free to also look at optional configuration for each field in the ISO message.

Feel free to take a look at a clearer documentation for repacking messages [here](https://github.com/chuksynaza/cISO8583/blob/master/README.md#ciso8583pack)

For unpacking messages look [here](https://github.com/chuksynaza/cISO8583/blob/master/README.md#ciso8583unpack)

Also note that this is a Javascript library and is available on npm.

Feel free to add more comments if you need any help or have any issues.
